// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "includeSubfolders": boolean;
      "subfoldersToSubcollections": boolean;
      "tagDuplicates": boolean;
      "importPDF": boolean;
      "importEPUB": boolean;
      "importHTML": boolean;
      "importOtherTypes": boolean;
      "retrieveMetadata": boolean;
      "showToolbarButton": boolean;
    };
  }
}
